language: rust

rust:
  - stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench

branches:
  only:
  - master

addons:
  artifacts: true
    s3_region: "eu-central-1"
    paths:
      - ./ecs/target/criterion
    debug: true
