language: rust

rust:
  - stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench

branches:
  only:
  - master

addons:
  artifacts:
    s3_region: "eu-central-1"
    debug: true