[package]
name = "phys"
version = "0.1.0"
authors = ["Govind Venkatesh <venkateshgovind1@gmail.com>"]
edition = "2018"

[dependencies]
ecs = {path = "../ecs"}
kiss3d = "0.18.0"
nphysics3d = "0.10.3"
ncollide3d = "0.18.3"
nalgebra = "0.17.2"