[package]
name = "papi"
version = "0.3.0"
authors = ["Eric Holk <eric.holk@gmail.com>", "Govind Venkatesh <gv45@sussex.ac.uk>"]

[dependencies]
libc = "^0.1.8"
rand = "^0.3.8"
ecs = {path = "../ecs"}
gnuplot = "0.0.29"

[profile.cache]
opt-level = 0